#!/usr/bin/env bash
# setup-fieldbrain-ubuntu.sh — provision an Ubuntu/Debian laptop as the 32PiScanner "field brain".
#
# Installs and configures the three rig services on one box:
#   • DHCP  via dnsmasq   (leases the Pis their IPs)
#   • NTP   via chrony    (LAN time source; keeps trigger sync tight)
#   • SMB   via Samba     (//<ip>/scans — where captured JPEGs land)
#
# Idempotent: safe to re-run. Any file it overwrites is backed up once as <file>.orig.
# Target: Ubuntu/Debian/Kali Desktop (NetworkManager + ufw).
#
# Usage:
#   sudo RIG_NIC=enp0s31f6 SMB_PASS=secret ./setup-fieldbrain-ubuntu.sh
#
# Optional overrides (defaults shown):
#   RIG_IP=192.168.50.1  RIG_CIDR=24
#   DHCP_START=192.168.50.100  DHCP_END=192.168.50.200
#   SMB_USER=scanner  SHARE_DIR=/srv/scans
set -euo pipefail

# ── config ──────────────────────────────────────────────────────────────────
RIG_IP="${RIG_IP:-192.168.50.1}"
RIG_CIDR="${RIG_CIDR:-24}"
DHCP_START="${DHCP_START:-192.168.50.100}"
DHCP_END="${DHCP_END:-192.168.50.200}"
SMB_USER="${SMB_USER:-scanner}"
SHARE_DIR="${SHARE_DIR:-/srv/scans}"
CON_NAME="rig"
SUBNET="$(echo "$RIG_IP" | awk -F. '{printf "%s.%s.%s.0", $1,$2,$3}')/${RIG_CIDR}"

log(){ printf '\033[1;32m[fieldbrain]\033[0m %s\n' "$*"; }
err(){ printf '\033[1;31m[fieldbrain] ERROR:\033[0m %s\n' "$*" >&2; }
backup_once(){ if [[ -f "$1" && ! -f "$1.orig" ]]; then cp -a "$1" "$1.orig"; log "backed up $1 → $1.orig"; fi; }

# ── preflight ───────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || { err "run as root (sudo)"; exit 1; }

if [[ -z "${RIG_NIC:-}" ]]; then
  err "RIG_NIC not set. Wired interfaces on this machine:"
  ip -o link show | awk -F': ' '$2 !~ /lo|wl/ {print "    " $2}' >&2
  err "Re-run:  sudo RIG_NIC=<iface> SMB_PASS=<pw> $0"
  exit 1
fi
ip link show "$RIG_NIC" >/dev/null 2>&1 || { err "interface '$RIG_NIC' not found"; exit 1; }

if ! command -v nmcli >/dev/null 2>&1; then
  err "nmcli not found — this script assumes NetworkManager (Ubuntu Desktop)."
  err "On a netplan/systemd-networkd server, set the static IP manually and comment out step 3."
  exit 1
fi

if [[ -z "${SMB_PASS:-}" ]]; then
  if [[ -t 0 ]]; then
    read -r -s -p "SMB password for user '$SMB_USER': " SMB_PASS; echo
    [[ -n "$SMB_PASS" ]] || { err "empty password"; exit 1; }
  else
    err "SMB_PASS not set and no TTY to prompt. Pass SMB_PASS=..."; exit 1
  fi
fi

log "field brain = $RIG_IP/$RIG_CIDR on $RIG_NIC | DHCP $DHCP_START-$DHCP_END | share $SHARE_DIR"

# ── 1. packages ─────────────────────────────────────────────────────────────
log "installing packages (apt)"
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y chrony dnsmasq samba smbclient

# ── 2. don't sleep ──────────────────────────────────────────────────────────
log "masking sleep/suspend targets"
systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target >/dev/null 2>&1 || true

# ── 3. static IP (NetworkManager) ───────────────────────────────────────────
log "configuring static IP on $RIG_NIC (con '$CON_NAME')"
nmcli con delete "$CON_NAME" >/dev/null 2>&1 || true
nmcli con add type ethernet ifname "$RIG_NIC" con-name "$CON_NAME" \
    ipv4.method manual ipv4.addresses "$RIG_IP/$RIG_CIDR" \
    ipv4.gateway "" ipv4.dns "" ipv6.method disabled autoconnect yes >/dev/null
nmcli con up "$CON_NAME" >/dev/null

# Limited-broadcast route: cli.py broadcasts to 255.255.255.255, which has no
# matching route on an offline rig (no default gateway) -> "network unreachable".
# Pin it to the connection (persists across reboots) and apply it now.
nmcli con mod "$CON_NAME" +ipv4.routes "255.255.255.255/32" >/dev/null 2>&1 || true
nmcli con up "$CON_NAME" >/dev/null 2>&1 || true
ip route replace 255.255.255.255/32 dev "$RIG_NIC" 2>/dev/null || true

# ── 4. NTP (chrony server) ──────────────────────────────────────────────────
log "writing /etc/chrony/chrony.conf (serving $SUBNET)"
backup_once /etc/chrony/chrony.conf
cat > /etc/chrony/chrony.conf <<EOF
# 32PiScanner field-brain NTP server — generated by setup-fieldbrain-ubuntu.sh
# Upstream (only used when online; harmless offline).
pool pool.ntp.org iburst maxsources 4
# Serve time to the rig.
allow ${SUBNET}
# Offline: keep serving our own clock so the Pis still converge on us.
local stratum 10
makestep 1.0 3
rtcsync
driftfile /var/lib/chrony/chrony.drift
EOF
systemctl enable --now chrony >/dev/null
systemctl restart chrony

# ── 5. DHCP (dnsmasq) ───────────────────────────────────────────────────────
log "writing /etc/dnsmasq.conf"
backup_once /etc/dnsmasq.conf
cat > /etc/dnsmasq.conf <<EOF
# 32PiScanner field-brain DHCP — generated by setup-fieldbrain-ubuntu.sh
port=0                          # DHCP only, no DNS (avoids systemd-resolved on :53)
interface=${RIG_NIC}
bind-interfaces
dhcp-range=${DHCP_START},${DHCP_END},12h
dhcp-option=42,${RIG_IP}        # option 42 = NTP server (informational)
dhcp-option=3                   # no gateway (offline field rig)
dhcp-option=6                   # no DNS
EOF
systemctl enable --now dnsmasq >/dev/null
systemctl restart dnsmasq

# ── 6. SMB user + share dir ─────────────────────────────────────────────────
log "creating SMB user '$SMB_USER' + $SHARE_DIR"
id "$SMB_USER" >/dev/null 2>&1 || useradd -M -s /usr/sbin/nologin "$SMB_USER"
printf '%s\n%s\n' "$SMB_PASS" "$SMB_PASS" | smbpasswd -s -a "$SMB_USER" >/dev/null
mkdir -p "$SHARE_DIR"
chown "$SMB_USER:$SMB_USER" "$SHARE_DIR"
chmod 0775 "$SHARE_DIR"

# ── 7. Samba share config ───────────────────────────────────────────────────
if grep -q '^\[scans\]' /etc/samba/smb.conf; then
  log "[scans] share already present — leaving smb.conf as-is"
else
  log "appending [scans] to /etc/samba/smb.conf"
  backup_once /etc/samba/smb.conf
  cat >> /etc/samba/smb.conf <<EOF

[scans]
   path = ${SHARE_DIR}
   read only = no
   guest ok = no
   valid users = ${SMB_USER}
   create mask = 0664
   directory mask = 0775
EOF
fi
testparm -s >/dev/null 2>&1 || { err "smb.conf failed testparm — check /etc/samba/smb.conf"; exit 1; }
systemctl enable --now smbd >/dev/null
systemctl restart smbd

# ── 8. firewall (ufw) ───────────────────────────────────────────────────────
if command -v ufw >/dev/null 2>&1; then
  log "allowing rig subnet $SUBNET through ufw"
  ufw allow from "$SUBNET" >/dev/null 2>&1 || true
  ufw status | grep -q "Status: active" || \
    log "note: ufw is inactive — the rule is stored and applies if you enable ufw"
fi

# ── done ────────────────────────────────────────────────────────────────────
cat <<EOF

$(log "✓ field brain ready")

Verify:
  ip addr show ${RIG_NIC}          # -> ${RIG_IP}/${RIG_CIDR}
  chronyc tracking                 # chrony running
  systemctl status dnsmasq smbd    # both active
  smbclient -L localhost -U ${SMB_USER}   # lists 'scans'

Next: install the Pis with  sudo NTP_SERVER=${RIG_IP} ./install.sh
      and set their SMB creds (user=${SMB_USER}) to the password you just entered.
EOF
